const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const escapeHtml=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
let siteData=null;
async function loadSite(){try{const r=await fetch('/data/site.json',{cache:'no-store'});siteData=await r.json()}catch(e){console.error(e);siteData={}}renderSite()}
function renderSite(){
 const d=siteData||{};
 if(d.heroSlides){$$('[data-hero-slide]').forEach((slide,i)=>{const item=d.heroSlides[i],img=$('img',slide);if(item&&img)img.src=item.image});$$('[data-hero-panel]').forEach((panel,i)=>{const item=d.heroSlides[i];if(!item)return;const map=[['[data-hero-kicker]','kicker'],['[data-hero-title]','title'],['[data-hero-accent]','accent'],['[data-hero-intro]','intro']];map.forEach(([sel,key])=>{const el=$(sel,panel);if(el)el.textContent=item[key]||''});const c=$('[data-hero-cta]',panel);if(c){c.textContent=item.ctaLabel||'Explore';c.href=item.ctaHref||'/'}})}
 const grid=$('#serviceGrid');if(grid&&d.services)grid.innerHTML=d.services.map(s=>`<article class="style-card reveal"><img src="${s.image}" alt="${escapeHtml(s.name)} by Planit Hair" loading="lazy"><div class="style-card-content"><h3>${escapeHtml(s.name)}</h3><p>${escapeHtml(s.description)}</p><button type="button" data-book-treatment="${escapeHtml(s.name)}">Book this style</button></div></article>`).join('');
 const care=$('#aftercareList');if(care&&d.aftercare)care.innerHTML=d.aftercare.map((x,i)=>`<article class="care-row reveal"><span>0${i+1}</span><h3>${escapeHtml(x.title)}</h3><p>${escapeHtml(x.text)}</p></article>`).join('');
 renderGallery(d);renderPrices('women');renderBooking(d);syncLinks(d);wireBookButtons();observeReveals()
}
function renderGallery(d){$$('[data-gallery]').forEach(el=>{const limit=Number(el.dataset.galleryLimit||0),items=limit?(d.gallery||[]).slice(0,limit):(d.gallery||[]);el.innerHTML=items.map((x,i)=>`<button class="gallery-card reveal" type="button" data-book-treatment="${escapeHtml(x.treatment||'')}"><img src="${x.image}" alt="${escapeHtml(x.title)} by Planit Hair" loading="lazy"><span class="gallery-card-shade"></span><span class="gallery-card-meta"><small>${String(i+1).padStart(2,'0')}</small><strong>${escapeHtml(x.title)}</strong><i>↗</i></span></button>`).join('')})}
function renderPrices(cat){const list=$('#priceList');if(!list||!siteData?.pricing)return;const data=siteData.pricing[cat]||[];list.innerHTML=data.map((x,i)=>`<details class="price-item" ${i===0?'open':''}><summary><h3>${escapeHtml(x.name)}</h3><span class="price-from">from ${escapeHtml(x.from)}</span><span class="price-toggle">+</span></summary><div class="price-options">${(x.items||[]).map(y=>`<div class="price-row"><span>${escapeHtml(y.label)}</span><strong>${escapeHtml(y.price)}</strong></div>`).join('')}</div></details>`).join('');const note=$('#priceNote');if(note)note.textContent=siteData.priceNotes?.[cat]||'';$$('.price-item').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)$$('.price-item').forEach(o=>{if(o!==item)o.open=false})}))}
function renderBooking(d){const t=$('#treatment');if(t){const names=[...new Set([...(d.pricing?.women||[]),...(d.pricing?.men||[])].map(x=>x.name))];t.innerHTML='<option value="">Choose treatment</option>'+names.map(n=>`<option value="${escapeHtml(n)}">${escapeHtml(n)}</option>`).join('');const q=new URLSearchParams(location.search).get('treatment');if(q&&names.includes(q))t.value=q}
 const time=$('#time');if(time){const start=480,end=1260,step=15;time.innerHTML='<option value="">Choose time</option>';for(let m=start;m<=end;m+=step){const v=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;time.insertAdjacentHTML('beforeend',`<option value="${v}">${v}</option>`)}}
 const date=$('#date');if(date)date.min=new Date().toISOString().split('T')[0];
 const h=$('#bookingHeadline');if(h&&d.booking?.headline)h.textContent=d.booking.headline;const tx=$('#bookingText');if(tx&&d.booking?.text)tx.textContent=d.booking.text;const n=$('#availabilityNote');if(n&&d.booking?.availabilityNote)n.textContent=d.booking.availabilityNote;
 const form=$('#bookingForm');if(form&&!form.dataset.wired){form.dataset.wired='1';form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const fd=new FormData(form),phone=(d.contact?.whatsapp||'31634893324').replace(/\D/g,''),msg=`Hi Planit Hair,\n\nI would like to request an appointment.\n\nTreatment: ${fd.get('treatment')}\nDate: ${fd.get('date')}\nTime: ${fd.get('time')}\nName: ${fd.get('name')}${fd.get('notes')?`\n\nExtra information: ${fd.get('notes')}`:''}`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`,'_blank','noopener')})}}
function syncLinks(d){$$('[data-instagram]').forEach(a=>{if(d.contact?.instagram)a.href=d.contact.instagram});$$('[data-tiktok]').forEach(a=>{if(d.contact?.tiktok)a.href=d.contact.tiktok});$$('[data-whatsapp-direct]').forEach(a=>{const p=(d.contact?.whatsapp||'').replace(/\D/g,'');if(p)a.href='https://wa.me/'+p})}
function wireBookButtons(){$$('[data-book-treatment]').forEach(btn=>{if(btn.dataset.wired)return;btn.dataset.wired='1';btn.addEventListener('click',()=>{const tr=btn.dataset.bookTreatment||'';location.href='/book?treatment='+encodeURIComponent(tr)})})}
function observeReveals(){const els=$$('.reveal:not(.is-visible)');if(matchMedia('(prefers-reduced-motion: reduce)').matches){els.forEach(x=>x.classList.add('is-visible'));return}if(!('IntersectionObserver'in window)){els.forEach(x=>x.classList.add('is-visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.1});els.forEach(x=>io.observe(x))}
const mb=$('.menu-button'),mm=$('#mobileMenu');mb?.addEventListener('click',()=>{const open=mb.getAttribute('aria-expanded')==='true';mb.setAttribute('aria-expanded',String(!open));if(mm)mm.hidden=open});$$('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>{if(mm)mm.hidden=true;mb?.setAttribute('aria-expanded','false')}));
const page=document.body.dataset.page;$$('[data-nav]').forEach(a=>a.classList.toggle('is-active',a.dataset.nav===page));
$$('[data-price-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-price-tab]').forEach(x=>{x.classList.toggle('is-active',x===b);x.setAttribute('aria-selected',String(x===b))});renderPrices(b.dataset.priceTab)}));
const hero=$('.hero-story'),slides=$$('[data-hero-slide]'),panels=$$('[data-hero-panel]'),dots=$$('[data-hero-progress]'),count=$('.hero-frame-count strong'),next=$('.hero-next-control'),nextLabel=$('.hero-next-label'),reduce=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,lock=false,acc=0,startY=null,lastY=null;
function setFrame(n){if(!slides.length)return;frame=Math.max(0,Math.min(slides.length-1,n));slides.forEach((x,i)=>x.classList.toggle('is-active',i===frame));panels.forEach((x,i)=>{x.classList.toggle('is-active',i===frame);x.setAttribute('aria-hidden',String(i!==frame))});dots.forEach((x,i)=>x.classList.toggle('is-active',i===frame));if(count)count.textContent=String(frame+1).padStart(2,'0');if(nextLabel)nextLabel.textContent=frame===slides.length-1?'Enter site':'Swipe / scroll'}
function heroVisible(){if(!hero)return false;const r=hero.getBoundingClientRect(),h=innerWidth<=900?66:78;return r.top<=h+2&&r.bottom>h+160}
function stepHero(dir){if(lock||reduce.matches)return;if(dir>0){if(frame<slides.length-1)setFrame(frame+1);else hero.nextElementSibling?.scrollIntoView({behavior:'smooth'})}else if(frame>0)setFrame(frame-1);lock=true;setTimeout(()=>{lock=false;acc=0},520)}
dots.forEach((d,i)=>d.addEventListener('click',()=>setFrame(i)));next?.addEventListener('click',()=>stepHero(1));
addEventListener('wheel',e=>{if(!heroVisible()||reduce.matches)return;const dir=Math.sign(e.deltaY);if(dir<0&&frame===0)return;e.preventDefault();if(lock)return;acc+=e.deltaY;if(Math.abs(acc)>34)stepHero(acc>0?1:-1)},{passive:false});
hero?.addEventListener('touchstart',e=>{startY=e.touches[0]?.clientY??null;lastY=startY},{passive:true});hero?.addEventListener('touchmove',e=>{if(startY===null)return;lastY=e.touches[0]?.clientY??lastY;const d=lastY-startY;if((d<0&&frame<=slides.length-1)||(d>0&&frame>0))e.preventDefault()},{passive:false});hero?.addEventListener('touchend',()=>{if(startY===null||lastY===null)return;const d=lastY-startY;startY=null;lastY=null;if(Math.abs(d)>42)stepHero(d<0?1:-1)},{passive:true});if(hero)setFrame(0);
async function hydrate(v){if(v.dataset.ready)return v;const s=v.querySelector('source[data-chunk-prefix]');if(!s)return v;const arr=[];for(let i=0;i<Number(s.dataset.chunkCount||0);i++){const r=await fetch(s.dataset.chunkPrefix+String(i).padStart(2,'0')+'.b64');const bin=atob((await r.text()).replace(/\s+/g,'')),u=new Uint8Array(bin.length);for(let j=0;j<bin.length;j++)u[j]=bin.charCodeAt(j);arr.push(u)}v.src=URL.createObjectURL(new Blob(arr,{type:'video/mp4'}));v.dataset.ready='1';v.muted=true;v.loop=true;v.playsInline=true;v.load();return v}
const vids=$$('.social-card video');if(vids.length&&'IntersectionObserver'in window){const ratios=new Map(vids.map(v=>[v,0]));const stop=v=>{v.pause();try{v.currentTime=0}catch{}};const sync=()=>{let best=null,r=0;ratios.forEach((x,v)=>{if(x>r){r=x;best=v}});if(!best||r<.62){vids.forEach(stop);return}vids.forEach(v=>{if(v!==best)stop(v)});hydrate(best).then(()=>{if((ratios.get(best)||0)>=.62){best.muted=true;best.play().catch(()=>{})}})};const io=new IntersectionObserver(es=>{es.forEach(e=>ratios.set(e.target,e.isIntersecting?e.intersectionRatio:0));sync()},{threshold:[0,.3,.62,.9]});vids.forEach(v=>io.observe(v))}
const mobileBook=$('.mobile-book');if(mobileBook&&'IntersectionObserver'in window){const hidden=new Set(),io=new IntersectionObserver(es=>{es.forEach(e=>e.isIntersecting?hidden.add(e.target):hidden.delete(e.target));mobileBook.classList.toggle('is-hidden',hidden.size>0)},{threshold:.04});$$('.hero-story,.booking-section').forEach(x=>io.observe(x))}
if($('#year'))$('#year').textContent=new Date().getFullYear();loadSite();observeReveals();